// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuickMeals.Data;

namespace QuickMeals.Migrations.QuickMeals
{
    [DbContext(typeof(QuickMealsContext))]
    [Migration("20200718191955_validation")]
    partial class validation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("QuickMeals.Models.Authentication.Role", b =>
                {
                    b.Property<int?>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleID");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("QuickMeals.Models.Authentication.User", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15);

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.HasKey("Username");

                    b.HasIndex("RoleID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("QuickMeals.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CookTime")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username1")
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("RecipeId");

                    b.HasIndex("Username1");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            CookTime = 30,
                            Description = "1. Coat chicken breasts with onion and garlic powders and herbs. Season generously with salt and pepper. 2. Heat1 Tablespoon of oil and cook chicken breasts. Transfer to plate. 3. Heat oil and saute garlic, parsley, thyme and rosemary. 4. Stir in milk or cream. 5. Bring to a boil. Add cornstarch and stir until thickened. 6. Return chicken to skillet and sprinkle extra herbs if desired.",
                            Ingredients = "Chicken, garlic, oil, parsley, thyme, rosemary and milk",
                            Title = "Creamy Herb Chicken",
                            Username = ""
                        },
                        new
                        {
                            RecipeId = 2,
                            CookTime = 15,
                            Description = "1. Heat oil over medium heat. 2. Lightly season the cubed chicken with salt and pepper. 3. Add the chicken to the skillet and brown on one side. 4. Make the glaze. Whisk the honey, soy sauce, garlic, and red pepper flakes in a small bowl. 5. Add the sauce to the pan and toss to coat chicken. Cook until chicken is done. 6. Serve on steamed rice.",
                            Ingredients = "Olive oil, chicken breast, honey, soy sauce, garlic, red pepper flakes, salt and pepper",
                            Title = "Garlic Honey Chicken",
                            Username = ""
                        });
                });

            modelBuilder.Entity("QuickMeals.Models.Authentication.User", b =>
                {
                    b.HasOne("QuickMeals.Models.Authentication.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuickMeals.Models.Recipe", b =>
                {
                    b.HasOne("QuickMeals.Models.Authentication.User", "User")
                        .WithMany("Recipies")
                        .HasForeignKey("Username1");
                });
#pragma warning restore 612, 618
        }
    }
}
